FROM public.ecr.aws/sam/build-provided.al2023
WORKDIR /build
COPY *.c *.h ./
COPY template.yaml samconfig.toml ./
RUN mkdir -p target
RUN gcc -O3 -DRELEASE -o target/bootstrap runtime.c function.c
RUN strip -s target/bootstrap
CMD ["sam", "deploy"]
